#' Reads in HOMER tags file
#'
#' @param fn path to file and filename of tags generated by HOMER.
#' @param coord A vector with three elements c(chrom, start, end) like c(7, 110901160, 111101971).
#' @return A cleaned-up data frame of HOMER tags.
#' @examples
#' -
##
#' @export

read_homer <- function(fn, coord){

  if(missing(coord)) stop('Chromosome coordinates missing')
  if(missing(fn)) stop('Hicup filename missing')

  # upload homer file
  tags<-read.delim(fn, header=FALSE, stringsAsFactors=FALSE)

  # bgmodel:
  # [chrN_read_1; pos_read_1; chrN_read_2; pos_read_2; counts]
  # chr7 3188777 chr7  17687771   40
  # chr7 3238846 chr7  27313134   25
  bgmodel <- cbind(tags[, 2:3], tags[, 7:8], tags[, 5])
  # fix chrom name
  bgmodel[,1] <- gsub("^chr", "", bgmodel[,1])
  bgmodel[,3] <- gsub("^chr", "", bgmodel[,3])

  coord <- as.integer(coord)

  # get chromosome
  bgmodel <- bgmodel[bgmodel[, 1] == coord[1] & bgmodel[, 3] == coord[1], ]
  # get forward range
  bgmodel <- bgmodel[bgmodel[, 2] >= coord[2] & bgmodel[, 2] <= coord[3], ]
  # get reverse range
  bgmodel <- bgmodel[bgmodel[, 4] >= coord[2] & bgmodel[, 4] <= coord[3], ]

  attr(bgmodel, "class") <- c('data.frame', 'homer')
  return(bgmodel)
}
