#' Preparing a data frame of zeros to cover the background for visualization in heatmap3
#'
#' @param truncated_m A final, normalized interaction matrix generated by truncate_matrix().
#' @return A dataframe of zeros to cover background for visualization.
#' @export
blackout_cells<-function(truncated_m){
  if(missing(truncated_m)) stop('missing truncated_m')
  if(!'truncated_m' %in% class(truncated_m)) stop('wrong class of truncated_m')
  coor <- which(truncated_m == 0, arr.ind = TRUE)
  cor <- which(lower.tri(truncated_m,diag = FALSE) == FALSE, arr.ind = TRUE)
  coord1 <- rbind(coor, cor)
  colorbl <- rep("black", times = nrow(coor))
  colorwh <- rep("white", times = nrow(cor))
  colordf <- append(colorbl, colorwh)
  data.frame(coord1, colordf)
}
