#' Generating restriction fragment sized bins
#'
#' @param regions Regions between restriction enzyme cutting sites.
#' @param inter_matrix A basic contact matrix generated by \code{inter_matrix} function.
#' 
#' @return A matrix of restriction fragment sized bins of class \code{rawbins}.
#'
#' @export
make_bins <- function(regions, inter_matrix){
  
  # tests
  if(missing(regions)) stop('regions missing')
  if(missing(inter_matrix)) stop('missing inter_matrix')
  if(!'hicup' %in% class(regions)) stop('wrong class of regions')
  if(!'raw.inter' %in% class(inter_matrix)) stop('wrong class of inter_matrix')

  row_summary <- row_sum(regions, inter_matrix)
  col_summary <- col_sum(regions, inter_matrix, row_summary)

  attr(col_summary, 'class') <- c(class(col_summary), 'rawbins')
  return(col_summary)
}
