#' Normalizing a binned contact matrix by dividing it by the sum of the reads in bins (mapping to both fragments involved in the interaction) 
#'
#' @param bins a matrix of restriction fragment sized bins generated by \code{make_bins} function.
#' @param norm_param A binned raw matrix generated by \code{norm_param} function.
#' 
#' @return A normalized contact matrix of class \code{normalized}.
#'
#' @export
normalization <-function(bins, norm_param){
  
  # tests
  if(missing(bins)) stop('missing bins')
  if(!'rawbins' %in% class(bins)) stop('wrong class of bins')
  if(missing(norm_param)) stop('missing norm_param')
  if(!'norm.param' %in% class(norm_param)) stop('wrong class of bins')
  
  normalized <- bins / norm_param
  normalized[is.nan(normalized)] <- 0

  attr(normalized, 'class') <- c(class(normalized), 'normalized')
  return(normalized)
}
