#' Limit extreme matrix values to a fraction of the maximum value of input matrix to improve visualization
#'
#' @param ext_matrix A matrix generated by extending_matrix().
#' @param limit A coefficient by which the maximum values is obtained - to be determined by trial and error.
#' @return A finished, extended interaction matrix which is used as an input to blackout_cells() and plot_results().
#' @examples
#' \dontrun{
#' truncated_m <- truncate_matrix(extended_matrix, limit = 0.25)
#' }
##
#' @export
truncate_matrix <- function(ext_matrix, limit=0.25){
  limit <- limit * max(ext_matrix)
  ext_matrix[ext_matrix >= limit] <- limit

  # add class
  attr(ext_matrix, 'class') <- c(class(ext_matrix), 'truncated_m')
  return(ext_matrix)
}
